##version: '2.1'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10      
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
 
  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.10   
    volumes:
      - ./src/main/resources/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044" 	
      - "9600:9600"	 
    depends_on:
      - elasticsearch
 
 
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.10   
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
 

 